services:
  neo4j:
    image: neo4j:2025.04.0-bullseye
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["graph-data-science"]
    volumes:
      - neo4j_volume:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7474"]

volumes:
  neo4j_volume: